name: voice_news
description: "A new Flutter project."
publish_to: "none"
version: 0.5.7+17

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  flutter_tts:
  flutter_riverpod:
  intl:
  url_launcher:
  webview_flutter:
  workmanager:
  device_preview:
  firebase_core: ^3.6.0
  cloud_functions: ^5.1.3
  googleapis_auth: ^1.6.0
  just_audio: ^0.9.41

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
