name: voice_news
description: "A new Flutter project."
publish_to: "none"
version: 0.3.3+10

environment:
  sdk: ^3.5.0

dependencies:
  flutter:
    sdk: flutter
  http:
  shared_preferences:
  flutter_tts:
  flutter_riverpod:
  intl:
  url_launcher:
  webview_flutter:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
